# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "your-client-id"
name = "DS Ambientes"
handle = "ds-ambientes"
application_url = "https://your-app-url.trycloudflare.com"
embedded = true

[access_scopes]
scopes = "read_products,write_draft_orders,read_customers"

[auth]
redirect_urls = [
  "https://your-app-url.trycloudflare.com/auth/callback",
  "https://your-app-url.trycloudflare.com/auth/shopify/callback",
  "https://your-app-url.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "your-dev-store.myshopify.com"
